Update Konten Statis
samdyra/website-IMG pull request #6
Opened 2024-01-02 15:49 UTC by alshaadiq

Samlikum bang sam, izin sundul

2024-01-02 16:19 UTC, samdyra requested changes
codewise OK, tp tolong image nya di compress dulu gan @alshaadiq (max ~300kb), bebas pake apa aja contoh pake https://www.iloveimg.com/compress-image.

atau kalo mau bisa pake laman admin di website img, upload aja gambar yg mau di compress, nanti download lg, itu udah auto ke compress

Dengan kurangin bandwidth, cost webnya bisa berkurang (reference: https://firebase.google.com/pricing?hl=id)

2024-01-02 18:22 UTC, alshaadiq commented
udah gann, tapi aing sebenernya ga yakin bagian import url organogramnya, kayaknya merusak kerapihan

2024-01-03 03:49 UTC, samdyra approved these changes
LGTM

2024-01-03 03:49 UTC, samdyra commented on src/assets/object/Organogram.js
> +
next development, nanti tolong sekalian delete gambar yang gakepakenya, sama line yg di comment2 gini delete aja biar rapih gan

2024-01-03 03:50 UTC, merged

2024-01-03 04:16 UTC, alshaadiq commented on src/assets/object/Organogram.js
> +
oke siap gann, gambar gakepakenya udah di delete, cuma nanti dirapihin lagi aja yang bagian import url ituu